SOUND(ILLEGAL_MOVE, "illegalMove.wav"),
#define SOUND_ILLEGAL_ACTION SOUND_ILLEGAL_MOVE
SOUND(ACTION, "action.wav"),
#define SOUND_MOVE_ACTION SOUND_ACTION
#define SOUND_PLAYER_2_LEAVE SOUND_ACTION
#define SOUND_PLAYER_2_JOIN SOUND_ACTION
SOUND(DONE, "done.wav"),
SOUND(FIRE_GUN, "fire_gun.ogg"),
SOUND(EXPLOTION_HIT, "small_explotion.wav"),
#define SOUND_EXPLOTION_SINK SOUND_EXPLOTION_HIT
SOUND(FIRE_NUKE, "air_raid.ogg"),
SOUND(NUKE_HIT, "nuke.ogg"),

SOUND(ROTATE_TETRO, "block-rotate.mp3"),
SOUND(SLOW_HIT_TETRO, "slow-hit.mp3"),
SOUND(CLEAR_TETRO, "line-remove.mp3"),
SOUND(CLEAR4_TETRO, "line-removal4.mp3")
